config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  
  get 'b' => 'blog#home'
  get 'archives' => 'blog#archives'
  get 'b/:id' => 'blog#previous'

  resources :posts

  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron">
  <h2>
    This is the about page!
  </h2>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="center jumbotron">
  <h2>
    This is the contact page!
  </h2>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="center jumbotron">
  <h2>
    This is the help page!
  </h2>
</div>

app/views/static_pages/home.html.erb
<aside>
  <%= image_tag "tedkang.jpeg", :class => "circular" %> 
</aside>
<section class="main">
<h1 class="center">Ted Kang</h1>
<p class="contact center">
  <%= link_to content_tag(:i, " CV ", class: 'fa fa-file'), root_path << "tedtkang-2015.pdf" %>
  &bull;
  <%= link_to content_tag(:i, " Blog ", class: 'fa fa-pencil'), b_path %>
  &bull;
  <%= link_to content_tag(:i, nil, class: 'fa fa-linkedin-square') , "http://www.linkedin.com/in/tedtkang" %>
  &bull;
  <%= mail_to "tedtkang@gmail.com" do %>
    <%= fa_icon "envelope", class: "fa" %>
  <% end %>  
</p>
<p class="center">Software Engineer. Previously at Oracle, Zoosk, SimplyInsured.<br>
Currently interested in the intersection of technology and law.</p>
</section>