config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  
  get 'b' => 'blog#home'
  get 'archives' => 'blog#archives'
  get 'b/:id' => 'blog#previous'

  resources :posts

  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'

  

end

app/views/layouts/_blog_footer.html.erb
<footer>
  <p class="twitter">Thoughts?  Tell me on <a href="http://twitter.com/tkang">Twitter</a></p>
  <%= link_to content_tag(:i, " archives", class: 'fa fa-archive fa-lg archives'), archives_path %> 
</footer>

app/views/layouts/_blog_view.html.erb
<% if @post == nil %>
  Nothing to see here ... yet
<% else %>
  <h1 class="blog-title"><%= @post.title %></h1>
  <h2 class="blog-postdate"><%= @post.created_at.strftime('%B %d, %Y') %></h2>
  <%= simple_format @post.body %>
  <%= render 'layouts/blog_footer' %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    ted's base app
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_ganalytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1418161-4', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="header-container">
    <%= link_to content_tag(:i, "", class: 'fa fa-home fa-2x header-links'), root_path %>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= metamagic description: "Ted Taiho Kang: zug zug", keywords: ["ted kang", "ted taiho kang", "tedtkang", "tkang", "ted", "kang"] %>
    <%= favicon_link_tag 'favicon.ico' %>    
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/ganalytics' %>
    <!--  this was deployed thru cap v3!!-->
  </head>
  <body>
    <% if false %>
      <%= render 'layouts/header' %>
    <% end %>
    <div class="container">
      <% if false %>
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>    
      <% end %>
      <%= yield %>
      <% if false %>      
        <%= render 'layouts/footer' %>
      <% end %>
      <%= debug(params) if Rails.env.development? %>            
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= metamagic description: "Ted Taiho Kang: zug zug", keywords: ["ted kang", "ted taiho kang", "tedtkang", "tkang", "ted", "kang"] %>
    <%= favicon_link_tag 'favicon.ico' %>    
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/ganalytics' %>
    <!--  this was deployed thru cap v3!!-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>            
    </div>
  </body>
</html>